name: "Build musl static binary"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
      - name: Install musl tools
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: Build static musl binary
        run: |
          CGO_ENABLED=1 CC=musl-gcc go build -o DDBOT-musl \
            -ldflags '-w -s -extldflags "-static" \
            -X "github.com/cnxysoft/DDBOT-WSa/lsp.BuildTime=$(date --rfc-3339=seconds)" \
            -X github.com/cnxysoft/DDBOT-WSa/lsp.CommitId=${{ github.sha }}' \
            github.com/cnxysoft/DDBOT-WSa/cmd
      - name: Check binary type
        run: file ./DDBOT-musl
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DDBOT-musl
          path: ./DDBOT-musl
