name: "Build static Go binary"

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'
          cache: false   # 避免 tar 解压错误

      - name: Build fully static Go binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o DDBOT-musl \
            -ldflags '-w -s \
            -X "github.com/cnxysoft/DDBOT-WSa/lsp.BuildTime=$(date --rfc-3339=seconds)" \
            -X github.com/cnxysoft/DDBOT-WSa/lsp.CommitId=${GITHUB_SHA}' \
            github.com/cnxysoft/DDBOT-WSa/cmd

      - name: Check binary type
        run: file ./DDBOT-musl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DDBOT-musl
          path: ./DDBOT-musl
